version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR
      - REGION="${AWS_DEFAULT_REGION:-ap-south-1}"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"

  build:
    commands:
      - echo Building backend
      - docker build -t backend ./backend
      - docker tag backend:latest "$ECR_BACKEND_REPOSITORY_URI:latest"

      - echo Building frontend
      - docker build -t frontend ./frontend
      - docker tag frontend:latest "$ECR_FRONTEND_REPOSITORY_URI:latest"

  post_build:
    commands:
      - echo Pushing images
      - docker push "$ECR_BACKEND_REPOSITORY_URI:latest"
      - docker push "$ECR_FRONTEND_REPOSITORY_URI:latest"

    
      - echo "Deploying to EC2 via SSM"

      - |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Name,Values=my-ec2" \
          --parameters commands='[
            "REGION='"$AWS_DEFAULT_REGION"'",
            "ACCOUNT_ID='"$ACCOUNT_ID"'",

            "aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com",

            "docker rm -f backend || true",
            "docker rm -f frontend || true",

            "docker pull '"$ECR_BACKEND_REPOSITORY_URI"':latest",
            "docker pull '"$ECR_FRONTEND_REPOSITORY_URI"':latest",

            "docker run -d -p 5000:5000 --name backend '"$ECR_BACKEND_REPOSITORY_URI"':latest",
            "docker run -d -p 80:80 --name frontend '"$ECR_FRONTEND_REPOSITORY_URI"':latest"
          ]' \
          --region "$AWS_DEFAULT_REGION"
